# Generated by Django 5.0.4 on 2024-05-17 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0002_alter_approval_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseoutline.student'),
        ),
    ]
