# Generated by Django 5.0.4 on 2024-05-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0003_alter_evaluation_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='email',
        ),
    ]
