# Generated by Django 5.0.4 on 2024-05-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0004_alter_approval_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('lecturer', 'Giảng viên'), ('student', 'Sinh viên')], default='student', max_length=20),
        ),
    ]
