# Generated by Django 5.0.4 on 2024-05-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0004_remove_lecturer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
