# Generated by Django 5.0.4 on 2024-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0005_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
