# Generated by Django 5.0.4 on 2024-05-20 07:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0006_outline_is_approved_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
